In [1]:
from cls2d import *

In [11]:
import torch.nn.functional as F
import numpy as np

In [3]:
# model list
# timm.models.vit_small_patch16_224_in21k
# resnet50d
# vit_small_patch16_224_in21k
# vit_base_patch16_224_in21k
# swinv2_base_window12to16_192to256_22kft1k
# deit3_small_patch16_224_in21ft1k
# beit_base_patch16_224

In [3]:
model = Cls2d(model='resmlp_12_distilled_224')
model.lr = 1e-5
model.batch_size = 12
model.epochs = 30
model.pretrain = True
model.gpu = "0"
model.optimizer = 'radam'
# model.LabelSmoothing = 0.1
model.save = True

# model.resize_size = 280
# model.crop_size = 256

model.dataset = 'flower'
model.load_dataset('../../data/flower')
model.train()


/home/qizekun/anaconda3/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


training: 101%[**************************************************->]
 135.50990803699824
[epoch 1] train_loss: 0.305 val_loss: 0.079  test_accuracy: 97.581
training: 100%[*************************************************->]]
 137.2311647280003
[epoch 2] train_loss: 0.152 val_loss: 0.055  test_accuracy: 97.849
training: 100%[*************************************************->]]
 138.503581262019
[epoch 3] train_loss: 0.137 val_loss: 0.035  test_accuracy: 98.925
training: 100%[*************************************************->]]
 138.49366123098298
[epoch 4] train_loss: 0.121 val_loss: 0.062  test_accuracy: 98.656
training: 100%[*************************************************->]]
 138.69995427998947
[epoch 5] train_loss: 0.143 val_loss: 0.111  test_accuracy: 97.849
training: 100%[*************************************************->]]
 138.84360211499734
[epoch 6] train_loss: 0.149 val_loss: 0.070  test_accuracy: 98.925
training: 100%[*************************************************->]

KeyboardInterrupt: 

In [4]:
model = Cls2d(model='resmlp_12_distilled_224')
model.lr = 1e-5
model.batch_size = 32
model.epochs = 30
model.pretrain = True
model.gpu = "0"
model.optimizer = 'radam'
# model.LabelSmoothing = 0.1vit_large_patch16_224_in21k
model.save = True

model.dataset = 'flower'
model.load_dataset('../../data/flower')

model.pretrain_path = 'work_dir/cls2d/flower/resmlp_12_distilled_224/resmlp_12_distilled_224.pth'
feature, result = model.inference(image_path='../../data/flower/val/daisy/5673728_71b8cb57eb.jpg')
print(feature)
print(result)

tensor([[[ -0.7314,  -6.2715,   5.8027,  ...,  -1.8092, -12.3650,   1.7414],
         [  3.5016,  -6.1084,   8.0409,  ...,  -3.9806, -10.7852,  -3.0839],
         [ -5.2869,   3.6159,  13.1412,  ...,  -3.1867,  -9.7735, -14.8042],
         ...,
         [ -0.5645,  -0.2922,   1.7265,  ...,   2.8198,  -2.9246,  -5.4296],
         [  0.4297,   0.5441,   3.9934,  ...,   4.3536, -12.0629,  -2.9683],
         [  6.5544,   5.5490,  14.8346,  ...,  10.2959, -33.8330,  -0.4094]]],
       device='cuda:0', grad_fn=<AddcmulBackward0>)
tensor([[ 3.4205, -1.7524,  2.5466, -4.0340, -1.2080]], device='cuda:0',
       grad_fn=<AddmmBackward0>)


In [6]:
feature = feature.squeeze(0)

In [7]:
feature.shape

torch.Size([196, 384])

In [8]:
nf = F.normalize(feature, p=2, dim=1)

In [12]:
test = []
for i in range(len(nf)):
    test.append((nf[0] * nf[i]).sum().cpu().detach().numpy())
test = np.array(test)

In [13]:
test

array([ 1.00000000e+00,  7.55907059e-01,  5.29074907e-01,  1.50028929e-01,
        6.89192861e-02, -6.98245317e-02, -8.37925225e-02,  3.02345991e-01,
       -2.84211300e-02, -1.10890664e-01,  5.40837571e-02,  2.02993095e-01,
        1.28169417e-01,  1.86566561e-02, -6.48011789e-02,  2.44430244e-01,
        3.80336285e-01, -3.62310261e-02, -8.48628134e-02, -2.09203005e-01,
       -2.34309539e-01, -9.37954858e-02, -1.98078141e-01, -2.07107104e-02,
       -1.54597238e-01, -3.78677920e-02,  5.32149337e-02,  2.64923453e-01,
        6.67927980e-01,  4.52691853e-01,  5.42489104e-02, -1.05492495e-01,
        1.66309655e-01, -1.56064183e-01, -1.10797271e-01, -1.55973703e-01,
       -3.04991603e-01, -1.24436840e-02, -1.73000470e-01, -1.82665482e-01,
        1.99563295e-01,  2.76902132e-02,  6.22400761e-01,  3.30067396e-01,
        4.36978787e-02,  1.19995132e-01, -1.87902749e-01, -5.23677990e-02,
       -3.93205225e-01, -9.97738466e-02, -6.45835027e-02, -1.18057486e-02,
        3.70032713e-03, -

In [14]:
test.mean()

0.027689718

In [ ]:
t1 = F.normalize(torch.randn(1000), p=2, dim=0)
t2 = F.normalize(torch.randn(1000), p=2, dim=0)

In [ ]:
(t1*t2).sum()